import low_dimensional_manifolds_specific_dimension_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace low_dimensional_manifolds_specific_dimension_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end low_dimensional_manifolds_specific_dimension_theorem_canonical_lane_mathlib
end HautevilleHouse
